language: python
python:
  - "3.6"
  - "3.7"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install coveralls

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
after_success:
  - coveralls # submit coverage
